package main

var fileOfCardsMaster = []charSetStructKanji{

	{"車", "car", "vehicle",
		"ony: シャ (sha)",
		"kun: くるま (kuruma)",
		"自動車(jidousha; automobile), 電車(densha; train), 車体(shatai; car body), 車両(sharyou)",
		"新車(shinchya; new car), 車輪(sharin; wheel), 三輪車(sanrinsha; tricycle), 車軸(shajiku), ハンドル(handoru)"},

	{"日", "day", "sun",
		"ony: ジツ (jitsu:じつ), ニチ (nichi:にち)",
		"kun: ひ, か",
		"明日 (tomorrow)",
		" "},

	{"土", "earth", "soil, dirt, ground, mud, wet clay",
		"ony: ド, ト  (ど, と) do, to",
		"kun: つち (tsuchi)",
		"土曜日 - Saturday",
		" "},

	{"地", "earth", "land, place, solid ground",
		"ony: チ (chi); ジ (ji)",
		"kun: -",
		"地震(jishin; earthquake), 地域(chiiki; region), 土地(tochi; land)",
		"現地(genchi; site), 出身地(shusshin chi; hometown), 地名(chimei; place name)"},

	{"高", "expensive", "high, tall",
		"ony: コウ (kou); タカ (taka)",
		"kun: たか (taka)",
		"高い(takai; high), 最高(saikou; highest), 高原(kougen; plateau)",
		"高校(koukou; high school), 高層(kousou; high-rise), 高速(kousoku; high speed)\n" +
			"高い (expensive)"},

	{"魚", "fish", "seafood",
		"ony: ギョ (gyo), ぎょ (gyo)",
		"kun: さかな (sakana)",
		"魚 (fish)",
		"\ncompare bird:鳥"},

	{"足", "foot", "add, to add",
		"ソク (soku), そく (soku)",
		"kun: あし (ashi), ta(su) た(す)",
		"足 (foot)",
		" "},

	{"脚", "leg", "foot; base; foundation",
		" -",
		"kun: あし",
		" ",
		"Variant of Chinese: 腳  -  Foot足 or Leg脚, あし"},

	{"友", "friend", "companion",
		"ony: ユウ (yuu ゆう) ==== , 友人(yuujin; friend)",
		"kun: とも (tomo)",
		", 友好(yuukou; friendship), 親友(shin'yuu; close friend), 友達 (ともだち - activities friend)",
		"仲間(nakama; companion), 取引先(torihikisaki; business connection), 共同(kyoudou; joint)"},

	{"天", "heaven", "heavens or celestial sky 空",
		"ony: テン (ten), てん (ten)",
		"kun: あめ (ame), あま (ama)",
		"天気 (weather)",
		" "},

	{"空", "sky", "empty, emptiness, vacuum, void",
		"ony: クウ (kuu); ソラ (sora そら)",
		"kun: から (kara), くう, あける, あく, あき",
		"空港(kuukou; airport), 宇宙空間(uchuu kukan; outer space), 空腹(kuufuku; hunger)",
		"空っぽ (karappo; empty), 空く (aku; become empty), 空き家 (akai; vacant house), 空白 (kuuhaku; blank space)\n" +
			"空っぽ (kuuppo; empty), 空想 (kuusou; imagination), 空蝉 (kuusagi; empty shell)"},

	{"百", "hundred", "many, percent",
		"ony: ヒャク (hyaku)",
		"kun: -",
		"百日(hyakunichi; hundred days), 百人(hyakunin; hundred people), 百回(hyakkai; hundred times)",
		"百パーセント(hyaku paasento; one hundred percent), 二百(nihyaku; two hundred), 三百(sanbyaku; three hundred)\n" +
			"百万円 (1 million Yen)"},

	{"左", "left", "port, direction",
		"ony: サ (sa)",
		"kun: ひだり (hidari)",
		"左手(hidarite; left hand), 左翼(sayoku; left wing), 左折(sasetsu; turn left)",
		"左側(hidarigawa; left side)"},

	{"母", "mother", "parent",
		"ony: ボ (bo)",
		"kun: はは (haha)",
		"母親(hahaoya; mother), 母上(hahaue; mother), 義母(gibou; mother-in-law)",
		"お母さん(okaasan; mother), 母ちゃん(kachan; mom), ママ(mama; mom)"},

	{"古", "old", "former, antiquity",
		"ony: コ (ko)",
		"kun: ふる (furu-i)",
		"古典(koten; classic), 古代(kodai; ancient times), 古文(kobun; classical literature)",
		"古ぼける(fubokeru; grow old), 古着(furugi; old clothes)"},

	{"旧", "old", "former",
		"ony: キュウ (kyuu); コ(ko)",
		"kun: ふる (furui)",
		"旧友(kyuuyuu; old friend), 旧姓(kyuusei; maiden name), 旧弊(kyuuhai; old practice)",
		"昔(mukashi; in the past), 古い(furui; old), 用いられた(mochiirareru; used)"},

	{"老", "old", "aged",
		"ony: ロウ (rou)",
		"kun: お (o)いる",
		"老人(roujin), 高齢者(koureisha), 老齢(rouireki)",
		"老若男女(rounyounan), 老体(otai), 老衰(rousui); compare: person(formal):old 者:老"},

	{"雨", "rain", "wet, umbrella",
		"ony: ウ (u う)",
		"kun: あめ (ame)",
		"豪雨(gouu; heavy rain), 雨季(uuki; rainy season), 台風の雨(taifuu no ame; typhoon rain)",
		"傘(kasa; umbrella), 雨具(amagu; rainwear), 雨天(uenten; rainy weather)"},

	{"右", "right", "starboard, direction",
		"ony: ウ (u), ユウ　(yuu)",
		"kun: みぎ (migi)",
		"右手(migite; right hand), 右翼(uyoku; right wing), 右折(usettsu; turn right)",
		"右側(migigawa; right side), 坐る(suwaru; sit)\n" +
			"compare 名 name"},

	{"店", "shop", "store",
		"ony: てん (ten)",
		"kun: みせ (mise)",
		"喫茶店 (coffee shop)",
		" "},

	{"社", "shrine", "society",
		"ony: しゃ (sha)",
		"kun: やしろ (yashiro)",
		"社長 (president of a company)",
		" "},

	{"六", "six", "6, sextuple",
		"ony: ロク (roku)",
		"kun: む (mu)",
		"六日(muika; six days), 六人(rokunin; six people), 六回(rokkai; six times)",
		"六角(rokkaku; hexagon), 六月(rokugatsu; June), 六十(rokujuu; sixty), 六日(6th day of the month)"},

	{"駅", "station", "Train Station",
		"ony: えき (eki)",
		"kun: -",
		"駅前 (in front of the station)",
		" "},

	{"道", "street", "path, way",
		"ony: ドウ, どう (dou - the way) ",
		"kun: みち (michi) ",
		"道具 (tool)",
		" "},

	{"三", "three", "3",
		"ony: san さん",
		"kun: mi みか",
		"三日 3rd day of the month",
		" "},

	{"万", "ten thousand", "10 thousand",
		"ony: man まん, ban ばん",
		"kun: -",
		"万年筆 (fountain pen, ten thousand year brush)",
		" "},

	{"休", "rest", "vacation, to rest, break, take a break, holiday",
		"ony: キュウ(kyū)",
		"kun: やす(む)(yasumu), やす(み)(yasumi)",
		"休む (rest, to take a day off), 休暇を取る (take a break)",
		" "},

	{"水", "water", "agua, h2o",
		"ony: スイ (sui), すい (sui) ",
		"kun: みず (mizu)",
		"水曜日 (Wednesday)",
		"水兄弟 water brother/siblings"},

	{"白", "white", "blanca",
		"ony: ハク (haku はく), byaku びゃく",
		"kun: しろ (shiro), shiroi しろい",
		"白い (white), 面白い (interesting)",
		" "},

	{"本", "book", "origin, source",
		"ony: ホン (hon)",
		"kun: もと (moto)",
		"本屋(honya; bookstore), 本物(honmono; real thing), 日本(nihon; Japan), 日本語 (Japanese)",
		"本(hon; book), 本当(hontou; real), , , 元(moto; origin)"},

	{"火", "fire", "Tuesday",
		"ony: カ (ka)",
		"kun: ひ (hi)",
		"火事(kaji; fire), 火曜日(kayoubi; Tuesday), 炎(honoo; flame)",
		"火山(kazan; volcano), 火星(kasei; Mars), 花火(hanabi; fireworks)"},

	{"大", "big", "large, a lot",
		"ony: ダイ(dai); タイ(tai)",
		"kun: おお(oo)",
		"大変(dreadful, immense), 大きい(ookii; big), 大人(otona), 大学(daigaku)",
		"最大(saidai), 大量(tairyo), 巨大(kyodai)"},

	{"多", "many", "much, a lot",
		"ony: タ(ta)",
		"kun: おお(oo)",
		"多い(ooi; many), 多分(probably), 多数(tasuu), 多量(tairyo)",
		"豊富(houfu), 沢山(takusan), たくさん(takusan)"},

	{"飲", "to drink", "drink",
		"ony: -",
		"の　no(mu)",
		"飲み物 (beverage)",
		" "},

	{"飲み物", "beverage", "a drink",
		"ony: -",
		"のみもの (nomimono)",
		" ",
		"-\nMe likes to drink Drink/Beverage"},

	{"出", "to leave", "To go out",
		"ony: シュツ (shutsu)",
		"kun: で de(ru), だ da(su)",
		"出かける (to go out)",
		" "},

	{"入", "to enter", "to put in",
		"ony: ニュウ (nyuu) ??",
		"kun: はいる hai(ru), いれる i(reru) ???",
		"入口 (entrance)",
		" "},

	{"電", "electric", "electricity, electronics, electrical",
		"ony: デン(den)",
		"kun: -",
		"電気 (denki; electricity), 電子(denshi), 電力(denryoku)",
		"電源(dengen), 電波(denpa), 電卓(dentaku)\n" +
			"There's a power cord feeding Electricity into that jukebox "},

	{"七", "seven", "seventh",
		"ony: シチ (shichi)",
		"kun: なな (nana)",
		"七日(nanoka; seven days, 7th day of the month), 七人(shichinin; seven people), 七回(nanakai; seven times)",
		"七月(shichigatsu; July), 七十(nanajuu; seventy), 七色(nanairo; seven colors)"},

	{"中", "middle", "center, inner, between",
		"ony: チュウ (chuu)",
		"kun: なか (naka)",
		"日中 (during the day, midday)",
		" "},

	{"上", "above", "upper, up, superior",
		"ony: ジョウ(jou)",
		"kun: うえ(ue)",
		"上体(joutai; upper part of body), 上品(jouhin; high quality), 上手(ujou; skill)",
		"上着(jacket), 上がる(agaru; rise), 上る(noboru; ascend), 上野(Ueno)"},

	{"下", "below", "down, lower, descend",
		"ony: カ (ka),  --  ?  ゲ (ge ??) ??",
		"kun: した (shita)",
		"靴下 (socks), 下半身(kahanmi; lower half of body), 下品(gehin; low quality), 下手(heta; unskillful)",
		"下がる(sagaru; drop), 下る(kudaru; descend), 下町(shitamachi; downtown)"},

	{"五", "five", "quintuple",
		"ony: ゴ (go)",
		"kun: いつ (itsu)",
		"五日(itsuka; five days, 5th day of the month), 五人(gonin; five people), 五回(gokai; five times)",
		"五角(gokaku; pentagon), 五月(gogatsu; May), 五十(isso; fifty)"},

	{"女", "woman", "girl, female",
		"ony: ジョ (jo); ニョ(nyo)  --  jo じょ, nyo にょ",
		"kun: おんな (onna)",
		"女子の(joshino; girls, or all girls), 女子(joshi; girl), 女性(josei; female),  女房(nyoubou; wife)",
		"女の人(onna no hito; woman), 女らしい(onnarashii; feminine), 女子学生(joshigakusei; female student)"},

	{"口", "mouth", "opening",
		"ony: コウ (kou),  --  ? ku ?",
		"kun: くち (kuchi)",
		"出口 (exit)",
		" "},
}
