package main

var fileOfCardsInitiate = []charSetStructKanji{

	{"建築家 : けんちくか ", "architect", "designer", " -", " -",
		" – vocab",
		"Architect : けんちくか"},

	{"赤ちゃん (あか-ちゃん)", "baby", "infant", " -", " -",
		" – 私は赤女です  あかちゃん、(aka-chan)",
		" "},

	{"前", "before", "in-front", "ぜん", "まえ",
		"名前 (name)",
		" "},

	{"少年", "boy-small", "boy", " -", " -",
		" – 少 \"a little\": but can also mean \"few\"",
		"Small in years, boy?男, しょうねん"},

	{"歯医者 : しかい、、はいしゃ", "dentist", "orthodontist", " -", " -",
		" – vocab",
		"Dentist : (shikai, ha-isha)"},

	{"医者", "doctor", "physician", " -", " -",
		" – vocab ",
		"Doctor: いしゃ"},

	{"エンジニア", "engineer", "Engineer", " -", " -",
		" – vocab",
		" "},

	{"消防士 : しょうぼうし", "firefighter", "fireman", " -", " -",
		" – vocab",
		"Firefighter : しょうぼうし"},

	{"脚", "leg", "foot", " -", "あし",
		"foot; base; leg; foundation",
		"Variant of Chinese: 腳  -  Foot足 or Leg脚, あし"},

	{"先", "future", "ahead", "せん", "さき",
		"先週 (last week), 先生 (teacher, master)",
		"before "},

	{"少女", "girl-small", "baby-girl", " -", " -",
		" – 少 means \"a little\": but can also mean \"few\"",
		"Little Girl, 私は女の赤ちゃんです:I am a baby girl "},

	{"踵", "heel", "visit", "しょう (shō), しゅ (shu)", "かかと",
		"踵 of 足, heel of foot",
		"to follow; to visit; to call on  -  かかと Heel: to follow; to visit; to call on"},

	{"私 (わたし)", "I", "myself", " -", " -",
		"vocabulary: ",
		" "},

	{"あたし、私", "I-female", "female-I", " -", " -",
		"私は女です (I am a female [softer sounding]) ",
		"Softer ver of \"I\" used by females"},

	{"わたくし、私", "I-formal", "formal-I", " -", " -",
		"vocabulary: ",
		"Most formal version of Myself or I"},

	{"ぼく、僕", "I-male", "male-I", " -", " -",
		"僕は男です (I am a male)",
		"I, myself (boku, mainly used by males)"},

	{"おれ、俺", "I-male-casual", "I-male-informal", " -", " -",
		"俺は男です (I am a male[between friends])",
		"I, myself (mainly used by males [informal/casual])"},

	{"弁護士 : べんごし", "lawyer", "attorney", " -", " -",
		" – vocab",
		"Lawyer : べんごし"},

	{"看護師 : かんごし", "nurse", "Nurse: かんごし", " -", " -",
		" – vocab",
		" "},

	{"看護婦 : かんごふ", "nurse-female", "Female Nurse", " -", " -",
		" – vocab",
		" "},

	{"警察官 : けいさつかん", "police-officer", "cop", " -", " -",
		" – vocab",
		"Police Officer : けいさつかん"},

	{"政治家 : せいじか", "politician", "statesman", " -", " -",
		" – vocab",
		"Politician : せいじか"},

	{"歌手 : かしゅ", "singer", "vocalist", " -", " -",
		" – vocab",
		" "},

	{"兵士 : へいし", "soldier", "warrior", " -", " -",
		" – vocab",
		"soldier : へいし"},

	{"先生 : せんせい", "teacher", "instructor", " -", " -",
		" – vocab",
		"Teacher (sensei) : せんせい"},

	{"教師 : きょうし ", "teacher-academic", "academic-teacher", " -", " -",
		" – vocab",
		" "},

	{"時", "time", "hour", "じ", "とき",
		"時計 (clock, watch)",
		" "},

	{"若者", "youth", "young-person", "しゃく, にゃく", "わかい",
		"わかもの、若者 ",
		"Compare 老 meaning old or aged"},

	{"くちびる、唇", "lips",
		"-",
		"ony: -",
		"kun: -",
		"-",
		"-"},

	{"すね、脛", "shin",
		"-",
		"ony: -",
		"kun: -",
		"-",
		"-"},

	{"ひざ、膝", "knee",
		"-",
		"ony: -",
		"kun: -",
		"-",
		"-"},

	{"もも、腿", "thigh",
		"-",
		"ony: -",
		"kun: -",
		"-",
		"-"},

	{"あたま、頭", "head",
		"-",
		"ony: -",
		"kun: -",
		"-",
		"-"},

	{"かお、顔", "face",
		"-",
		"ony: -",
		"kun: -",
		"-",
		"-"},

	{"くち、口", "mouth",
		"-",
		"ony: -",
		"kun: -",
		"-",
		"-"},

	{"は、歯", "tooth",
		"teeth, dentures, dentition",
		"ony: -",
		"kun: -",
		"歯医者 : しかい、、はいしゃ, dentist",
		"-"},

	{"はな、鼻", "nose",
		"snozz, beak, proboscis",
		"ony: -",
		"kun: -",
		"-",
		"-"},

	{"め、目", "eye",
		"-",
		"ony: -",
		"kun: -",
		"-",
		"-"},
	/*
				{"ひげ、髭、鬚、髯", "moustache, beard",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かみ、髪", "hair",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"みみ、耳", "ear",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"おなか、御腹", "stomach",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"うで、腕", "arm",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひじ、肘", "elbow",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かた、肩", "shoulder",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"つめ、爪", "nail",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"て、手", "hand",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"てくび、手首", "wrist",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"てのひら、掌、手の平", "palm of hand (te-no-hira)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ゆび、指", "finger, toe (yubi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しり、尻", "buttocks (shiri)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"おなか、お腹 （はら、腹）", "abdomen (o-naka)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かんぞう、肝臓", "liver (kanzō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"きも、肝", "liver (kimo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"きんにく、筋肉", "muscle (kin'niku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"くび、首", "neck (kubi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"こころ、心", "heart [as in feelings] (kokoro)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"こし、腰", "waist, hip (koshi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しんぞう、心臓", "heart (shinzō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"せなか、背中", "back (senaka)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ち、血", "blood (chi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"にく、肉", "meat (niku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"はだ、肌、膚", "skin (hada)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひふ、皮膚", "skin (hifu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ほね、骨", "bone (hone)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"むね、胸", "chest (mune)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かぜ、風邪", "cold [illness] (kaze)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"げり、下痢", "diarrhea (geri)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"びょうき、病気", "illness (byōki)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かぞく、家族", "family (kazoku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"りょうしん、両親", "parents (ryoushin)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"こども、子供", "children, child (kodomo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ちち、父", "father (chichi)",
					"-",
					"ony: -",
					"kun: -",
					"six(\"otou-san\")",
					"-"},

				{"はは、母", "mother (haha)",
					"-",
					"ony: -",
					"kun: -",
					"six(\"okaa-san\")",
					"-"},

				{"つま、妻", "wife (tsuma)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"おっと、夫", "husband (otto)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あに、兄", "older brother (ani)",
					"-",
					"ony: -",
					"kun: -",
					"six (onī-san)",
					"-"},

				{"あね、姉", "older sister (ane)",
					"-",
					"ony: -",
					"kun: -",
					"six (onē-san)",
					"-"},

				{"おとうと、弟", "younger brother (otōto)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いもうと、妹", "younger sister (imōto)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"きょうだい、兄弟", "brothers, siblings (kyōdai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しまい、姉妹", "sisters (shimai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"そふ、祖父", "grandfather (sofu)",
					"-",
					"ony: -",
					"kun: -",
					"six (ojii-san)",
					"-"},

				{"そぼ、祖母", "grandmother (sobo)",
					"-",
					"ony: -",
					"kun: -",
					"six (obaa-san)",
					"-"},

				{"まご、孫", "grandchild (mago)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"おじ、伯父、叔父", "uncle (oji)",
					"-",
					"ony: -",
					"kun: -",
					"six (oji-san)",
					"-"},

				{"おば、伯母、叔母", "aunt (oba)",
					"-",
					"ony: -",
					"kun: -",
					"six (oba-san)",
					"-"},

				{"いとこ、従兄弟、従姉妹、従兄、従弟、従姉、従妹", "cousin (itoko)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"めい、姪", "niece (mei)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"おい、甥", "nephew (oi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いきもの、生き物", "living creatures (ikimono)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ばけもの、化け物", "monster (bakemono)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"どうぶつ、動物", "animal (dōbutsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"チーター", "cheetah (chītā)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いぬ、犬", "dog (inu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ねこ、猫", "cat (neko)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"うし、牛", "cow (ushi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ぶた、豚", "pig (buta)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"うま、馬", "horse (uma)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひつじ、羊", "sheep (hitsuji)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"さる、猿", "monkey (saru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ねずみ、鼠", "mouse, rat (nezumi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"とら、虎", "tiger (tora)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"オオカミ、狼", "wolf (ōkami)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"うさぎ、兎", "rabbit (usagi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"りゅう、たつ、竜", "dragon (ryū, tatsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しか、鹿", "deer (shika)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かえる、蛙", "frog (kaeru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"がま、蟇", "toad (gama)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しし、獅子", "lion (shishi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"キリン、麒麟", "giraffe (kirin)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ぞう、象", "elephant (zō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"とり、鳥", "bird (tori)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"にわとり、鶏", "chicken (niwatori)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},
		// to here

				{"じかん、時間", "time (jikan)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"とき、じ、時", "~hours (toki, ji)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"こよみ、カレンダー、暦", "calendar (koyomi, karendā)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ふん、分", "minute (fun)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"びょう、秒", "second (byō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひ、にち、日", "day (hi, nichi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"つき、がつ、月", "month (tsuki, gatsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"とし、ねん、年", "year (toshi, nen)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"きのう、さくじつ、昨日", "yesterday (kinō, sakujitsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"きょう、今日", "today (kyō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あした、あす、みょうにち、明日", "tomorrow (ashita, asu, myōnichi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あさ、朝", "morning (asa)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひる、昼", "afternoon (hiru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ゆうがた、夕方", "evening (yūgata)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ばん、晩", "evening (ban)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"よる、夜", "evening, night (yoru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ようび、曜日", "~day (yōbi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しゅう、週", "week (shū)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いっしゅうかん、一週間", "one week (isshūkan)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"にちようび、日曜日", "Sunday (nichi-yōbi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"げつようび、月曜日", "Monday (getsu-yōbi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かようび、火曜日", "Tuesday (ka-yōbi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"すいようび、水曜日", "Wednesday (sui-yōbi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"もくようび、木曜日", "Thursday (moku-yōbi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"きんようび、金曜日", "Friday (kin-yōbi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"どようび、土曜日", "Saturday (do-yōbi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"たいよう、太陽", "sun (taiyō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"つき、月", "moon (tsuki)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ほし、星", "star (hoshi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"てんき、天気", "weather (tenki)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"はれ、晴れ", "clear weather (hare)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あめ、雨", "rain (ame)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"くもり、曇り", "cloudy (kumori)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ゆき、雪", "snow (yuki)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かぜ、風", "wind (kaze)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かみなり、雷", "thunder, lightning (kaminari)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"たいふう、台風", "typhoon (taifū)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あらし、嵐", "storm (arashi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"そら、空", "sky (sora)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"きた、北", "north (kita)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひがし、東", "east (higashi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"みなみ、南", "south (minami)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"にし、西", "west (nishi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ここ", "here (koko)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"そこ", "there (soko)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あそこ", "over there (asoko)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"みぎ、右", "right (migi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひだり、左", "left (hidari)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"うえ、上", "above, up (ue)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"した、下", "below, down (shita)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"まえ、前", "front (mae)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"うしろ、後", "behind (ushiro)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"むこう、向こう", "the other side, opposite side (mukō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ななめ、斜め", "diagonal (naname)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"てまえ、手前", "nearer, more in front (temae)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"とおい、遠い", "far (tooi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ちかい、近い", "near, close (chikai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"みず、水", "water (mizu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ゆ、湯", "hot water (yu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"こおり、氷", "ice (kōri)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ゆげ、湯気", "steam (yuge)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひ、火", "fire (hi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ガス", "gas (gasu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"くうき、空気", "air, atmosphere (kūki)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"つち、土", "earth, ground (tsuchi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"きんぞく、金属", "metal, metallic (kinzoku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"どろ、泥", "mud, mire, clay, plaster (doro)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"けむり、煙", "smoke, tobacco, opium (kemuri)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"てつ、鉄", "iron [Fe] (tetsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"どう、銅", "copper [Cu] (dō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"きん、金", "gold [Au]",
					" money (kin)",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ぎん、銀", "silver [Ag]",
					" wealth (gin)",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"なまり、鉛", "lead [Pb] (namari)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しお、塩", "salt [NaCl] (shio)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"メートル", "meter (mētoru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"リットル", "litre (rittoru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"グラム", "gram (guramu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"キロ", "kilo- (kiro)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ミリ", "milli- (miri)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"センチメートル、センチ", "centimeter (senchi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"インチ", "inch (inchi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しゃかい、社会", "society (shakai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"けいざい、経済", "economy, economics (keizai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かいしゃ、会社", "company (kaisha)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かいぎ、会議", "meeting (kaigi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"がっこう、学校", "school (gakkō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"やくしょ、役所", "local government office (yakusho)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"みせ、店", "store (mise)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ホテル", "hotel (hoteru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"こうじょう、工場", "factory (kōjō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かね、金", "money (kane, most commonly o-kane)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"さつ、札", "bill [of money, e.g., a thousand-yen bill] (satsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"こぜに、小銭", "small change (kozeni)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"つりせん、釣り銭、おつり、お釣り", "change (tsurisen)",
					"-",
					"ony: -",
					"kun: -",
					"six, change (o-tsuri)",
					"-"},

				{"じどうはんばいき、自動販売機", "vending machine, slot machine (jidōhanbaiki)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"きっぷ、切符", "ticket (public transport, fine)",
					"-",
					"ony: -",
					"kun: -",
					"six (kippu)",
					"-"},

				{"きって、切手", "stamp (kitte)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"つくえ、机", "desk (tsukue)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いす、椅子", "chair, position (isu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"たたみ、畳", "a tatami mat (tatami)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"と、戸", "door, family (to)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"とびら、扉", "door panel (tobira)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ドア", "door (doa)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"まど、窓", "window (mado)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ふとん、布団", "futon (futon)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"げんかん、玄関", "entrance (genkan)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いえ、家", "house, home (ie)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"エレベーター", "elevator (erebētā)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"エスカレーター", "escalator (esukarētā)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"でんき、電気", "electricity (denki)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"くぎ、釘", "nail, spike (kugi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひも、紐", "string, cord (himo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"なわ、縄", "rope, string (nawa)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ふくろ、袋", "pocket, bag (fukuro)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かばん、鞄", "leather bag (kaban)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かさ、傘", "umbrella, parasol (kasa)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かぎ、鍵", "door bolt, key (kagi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ちょうこく、彫刻", "sculpture, engraving (chōkoku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ぶんぼうぐ、文房具", "stationery ​(bunbōgu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"インク", "ink (inku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ペン", "pen (pen)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ボールペン", "ball-point pen (bōrupen)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"まんねんひつ、万年筆", "fountain pen (mannenhitsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"えんぴつ、鉛筆", "pencil (enpitsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ふで、筆", "brush for writing or painting (fude)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"チョーク", "chalk (chōku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"けしゴム、消しゴム", "eraser (keshigomu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"えんぴつけずり、鉛筆削り", "pencil sharpener (enpitsu-kezuri)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"じょうぎ、定規", "ruler (jōgi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ノート", "notebook (nōto)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"にっき、日記", "diary (nikki)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"カバー", "book cover (kabā)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ふうとう、封筒", "envelope (fūtō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"はさみ、鋏", "scissors (hasami)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ホッチキス", "stapler (hotchikisu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ふく、服", "clothes (fuku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ようふく、洋服", "western clothing (yōfuku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"きもの、着物", "kimono (kimono)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"わふく、和服", "Japanese clothing (wafuku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"そで、袖", "sleeve (sode)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"えり、襟", "lapel, collar (eri)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ボタン", "button (botan)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"チャック、ファスナー、ジッパー", "zipper, zipper fastener (chakku, fasunā, jippā)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ベルト", "belt (beruto)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"くつ、靴", "shoe (kutsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"くつした、靴下", "sock (kutsushita)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"めがね、眼鏡", "glasses (megane)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"てつどう、鉄道", "railway (tetsudō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"えき、駅", "station (eki)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひこうき、飛行機", "airplane (hikōki)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"くうこう、空港 （ひこうじょう、飛行場）", "airport (kūkō, hikōjō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"みち、道", "street, way, road (michi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"どうろ、道路", "road (dōro)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"バスてい、バス停", "bus-stop (basutei)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"とおり、通り", "avenue (tōri)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"でんしゃ、電車", "train (densha)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"くるま、車 (じどうしゃ、自動車)", "-",
					"ony: -",
					"kun: -",
					"-",
					"car (kuruma, jidōsha)",
					"-"},

				{"じてんしゃ、自転車", "bicycle (Jitensha)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"もじ、文字", "letter, character, script (moji)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"じ、字", "a letter, character (ji)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かんじ、漢字", "Chinese character (kanji)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひらがな、平仮名", "hiragana syllabary characters (hiragana)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"カタカナ、片仮名", "katakana syllabary characters (katakana)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"すうじ、数字", "numbers (sūji)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"アルファベット", "alphabet (arufabetto)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ローマ字", "Roman characters, Latin script (rōmaji)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"がいこくご、外国語", "foreign language (gaikokugo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"にほんご、日本語 （こくご、国語）", "Japanese [language] (nihongo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"えいご、英語", "English [language] (eigo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ちゅうごくご、中国語", "Chinese [language] (chūgokugo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"どいつご、ドイツ語", "German [language] (doitsugo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"すぺいんご、スペイン語", "Spanish [language] (supeingo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ふらんすご、フランス語", "French [language] (furansugo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ちょうせんご、朝鮮語、かんこくご、韓国語", "Korean [language]",
					"South Korean [language] (chōsengo, kankokugo)",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ほん、本", "book (hon)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かみ、紙", "paper (kami)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"てがみ、手紙", "letter (tegami)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しんぶん、新聞", "newspaper (shinbun)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"じしょ、辞書", "dictionary (jisho)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"パソコン", "personal computer (pasokon)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いろ、色", "color (iro, shikisai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あか、赤", "red (aka)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"きいろ、黄色", "yellow (kiiro)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"みどり、緑", "green (midori)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あお、青", "blue (ao)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"むらさき、紫", "purple (murasaki, murasakiiro)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しろ、白", "white (shiro)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"くろ、黒", "black (kuro)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ピンク", "pink (pinku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ちゃいろ、茶色", "brown (chairo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"はいいろ、灰色、ねずみいろ、鼠色", "grey (haiiro, nezumiiro)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"オレンジ", "orange (orenji)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"え、絵", "picture (e)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"おんがく、音楽", "music (ongaku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"りか、理科", "science (rika)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"さんすう、算数", "arithmetic (sansū)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"れきし、歴史", "history (rekishi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ちり、地理", "geography (chiri)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"たいいく、体育", "physical education (taiiku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"スポーツ", "sport (supōtsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"システム", "system (shisutemu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"じょうほう、情報", "information, news (jōhō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひつよう、必要", "necessity (hitsuyō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"べんきょう、勉強", "study (benkyō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いらい、依頼", "request (irai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"れい、ゼロ、零", "zero (rei, zero)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いち、一", "one (ichi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"に、二", "two (ni)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"さん、三", "three (san)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"よん、し、四", "four (yon, shi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ご、五", "five (go)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ろく、六", "six (roku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"なな、しち、七", "seven (nana, shichi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"はち、八", "eight (hachi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"きゅう、く、九", "nine (kyū, ku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"じゅう、十", "ten (jū)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひゃく、百", "hundred (hyaku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"せん、千", "thousand (sen)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"まん、万", "ten thousand (man)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"おく、億", "one hundred million (oku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひとつ、一つ", "one, one thing (hitotsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ふたつ、二つ", "two, two things (futatsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"みっつ、三つ", "three, three things (mittsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"よっつ、四つ", "four, four things (yottsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いつつ、五つ", "five, five things (itsutsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"むっつ、六つ", "six, six things (muttsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ななつ、七つ", "seven, seven things (nanatsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"やっつ、八つ", "eight, eight things (yattsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ここのつ、九つ", "nine, nine things (kokonotsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"とお、十", "ten, ten things (tō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"これ", "this, it (kore)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"それ", "that (sore)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あれ", "that over there (are)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"どれ", "which (dore)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"こちら、こっち", "this direction (kochira, kocchi)",
					"thing, person, or place",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"そちら、そっち", "that direction, thing, person, or place (sochira, socchi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あちら、あっち", "that direction, thing, person, or place over there (achira, acchi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"どちら、どっち", "which direction, thing, person, or place (dochira, docchi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひみつ、秘密", "secret (himitsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"じどう、自動", "automatic (jidō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ないよう、内容", "content (naiyō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"はば、幅", "width",
					"breadth, free room, difference (between two substances)",
					"ony: -",
					"kun: -",
					"six (haba)",
					"-"},

				{"せいしき、正式", "formality (seishiki)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"けっこん、結婚", "marriage (kekkon)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"げんざい、現在", "now (genzai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いま、今", "now (ima)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かこ、過去", "past (kako)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"みらい、未来", "future (mirai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いい、よい、良い", "good (ii, yoi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"すごい、凄い", "amazing (sugoi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"すばらしい、素晴らしい", "wonderful (subarashii)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"わるい、悪い", "bad, inferior (warui)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"たかい、高い", "expensive, high (takai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひくい、低い", "low (hikui)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"やすい、安い", "cheap (yasui)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"おおきい、大きい", "big (ōkii)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ちいさい、小さい", "small (chiisai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ほそい、細い", "thin (hosoi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ふとい、太い", "thick (futoi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ふるい、古い", "old (furui)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あたらしい、新しい", "new (atarashii)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"わかい、若い", "young (wakai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かるい、軽い", "light, easy (karui)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"おもい、重い", "heavy (omoi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"やさしい、易しい", "easy (yasashii)",
					"simple",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"むずかしい、難しい", "difficult (muzukashii)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"やわらかい、柔らかい", "soft (yawarakai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かたい、硬い、堅い", "hard (katai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あつい、熱い、暑い", "hot (atsui)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"つめたい、冷たい", "cold (tsumetai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"さむい、寒い", "cold (samui)",
					"-",
					"ony: -",
					"kun: -",
					"six as in cold weather",
					"-"},

				{"おいしい、美味しい", "delicious (oishii)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"うまい、美味い、旨い", "delicious (umai)",
					"appetizing",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"まずい、不味い", "tastes awful (mazui)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あまい、甘い", "sweet (amai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"からい、辛い", "hot [spicy] (karai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しょっぱい、塩っぱい", "salty (shoppai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"にがい、苦い", "bitter (nigai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"うつくしい、美しい", "beautiful (utsukushii)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"うれしい、嬉しい", "happy (ureshii)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"たのしい、楽しい", "fun (tanoshii)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かなしい、悲しい", "sad (kanashii)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"さびしい、寂しい、淋しい", "lonely (sabishii)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"さみしい、寂しい、淋しい", "sad (samishii)",
					"lonely",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"こわい、怖い、恐い", "scary (kowai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いたい、痛い", "painful (itai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かゆい、痒い", "itchy (kayui)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"くさい、臭い", "stinky (kusai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"つらい、辛い", "painful (tsurai)",
					"heart-breaking",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"する", "to do (suru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"やる", "to do (yaru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いる", "to exist [for animate objects] (iru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ある", "to exist [for inanimate objects] (aru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"なる", "to become (naru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"おこる、起こる、興る", "to occur (okoru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あらわれる、現れる", "to appear (arawareru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いきる、生きる", "to live (ikiru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"うむ、生む、産む", "to give birth (umu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しぬ、死ぬ", "to die (shinu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"こわれる、壊れる", "to breakin (kowareru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いく、行く", "to go (iku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"くる、来る", "to come (kuru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かえる、帰る、返る", "to return (kaeru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あるく、歩く", "to walk (aruku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"とぶ、飛ぶ", "to jump, to fly (tobu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"およぐ、泳ぐ", "to swim (oyogu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"うごく、動く", "to move-in (ugoku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"おどる、踊る", "to dance (odoru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ねる、寝る", "to sleep (neru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"うたう、歌う", "to sing (utau)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かむ、噛む", "to bite (kamu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"たべる、食べる", "to eat (taberu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"のむ、飲む", "to drink (nomu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"さわる、触る", "to touch (sawaru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"なげる、投げる", "to throw (nageru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"もつ、持つ", "to hold (motsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"うつ、打つ", "to hit (utsu)",
					"to strike",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"なぐる、殴る", "to hit (naguru)",
					"to strike",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"さす、指す", "to point (sasu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"さす、刺す", "to stab (sasu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"さす、差す", "to raise or extend one's hands (sasu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ける、蹴る", "to kick (keru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"すわる、座る", "to sit (suwaru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"たつ、立つ", "to stand (tatsu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"はしる、走る", "to run (hashiru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あく、空く", "to become unoccupied (aku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"こむ、込む", "to be crowded (komu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いる、要る", "to need (iru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かわく、乾く", "to become dry (kawaku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"みだす、乱す", "to disturb (midasu)",
					"to disarrange",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"みだれる、乱れる", "to be disturbed (midareru)",
					"to become confused",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"つかえる、仕える", "to serve (tsukaeru)",
					"to work for",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"そなわる、備わる", "to be furnished with (sonawaru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"すぐれる、優れる", "to excel (sugureru)",
					"to surpass",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ひえる、冷える", "to grow cold (hieru)",
					"to get chilly, to cool down",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"さめる、覚める", "to wake (sameru)",
					"to become sober, to be disillusioned",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"さめる、冷める", "to cool down (sameru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"むく、向く", "to face, to turn toward (muku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"たおれる、倒れる", "to fall, to collapse (taoreru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かたまる、固まる", "to harden, to solidify, to become firm (katamaru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"うまる、埋まる", "to be filled, to be surrounded, to overflow (umaru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"うもれる、埋もれる", "to be buried, to be covered (umoreru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ます、増す", "to increase, to grow (masu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ふえる、増える", "to increase, to multiply (fueru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"へる、減る", "to decrease (heru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"はずれる、外れる", "to deviate (hazureru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ふとる、太る", "to grow fat (futoru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"はじまる、始まる", "to begin (hajimaru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"おわる、終わる", "to finish, to close (owaru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"きめる、決める", "to decide (kimeru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"みる、見る", "to see (miru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"きく、聞く、聴く", "to hear, to listen (kiku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"さわる、触る", "to touch, to feel (sawaru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かぐ、嗅ぐ", "to smell (kagu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いう、言う", "to say (iu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"はなす、話す", "to speak (hanasu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かたる、語る", "to tell (kataru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かく、書く", "to write (kaku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"よむ、読む", "to read (yomu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"つかう、使う", "to use (tsukau)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"つくる、作る、造る、創る", "to make (tsukuru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"なおす、直す、治す", "to fix, repair (naosu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"すてる、捨てる", "to discard, throw away (suteru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"とる、取る、撮る、採る", "to take (toru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"おく、置く", "to put (oku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かなしむ、悲しむ、哀しむ", "to be sad (kanashimu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"なく、泣く", "to cry (naku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"わらう、笑う", "to laugh (warau)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"おこる、怒る", "to be angry (okoru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ほめる、褒める", "to encourage (homeru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しかる、叱る", "to scold (shikaru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"よろこぶ、喜ぶ", "to celebrate (yorokobu)",
					"to be jubilant, to have joy, to have delight, to have rapture",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"よろこび、喜び", "joy, delight, rapture (yorokobi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"なぐさめる、慰める", "to console, to provide empathy (nagusameru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あきる、飽きる", "to be disinterested, to be bored, to be tired of, to be weary (akiru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"おどろく、驚く", "to be astonished, to be surprised, to be scared (odoroku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あう、会う", "to meet, to interview (au)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あける、開ける", "to opentr, to unwraptr (akeru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あそぶ、遊ぶ", "to play (asobu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あつまる、集まる", "to gatherin (atsumaru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"うる、売る", "to sell (uru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"える、得る", "to obtain [some benefit or knowledge] (eru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"おる、折る", "to breaktr, to foldtr (oru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かう、買う", "to buy (kau)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"きる、切る", "to cut (kiru)",
					"-",
					"ony: -",
					"kun: -",
					"six†",
					"-"},

				{"きる、着る", "to wear [on the upper body] (kiru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"はく、履く", "to wear [on the lower body] (haku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かえる、変える", "to change (kaeru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かえる、代える", "to exchange, to substitute, to replace (kaeru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しめる、閉める", "to close (shimeru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しめる、締める", "to tie, to fasten (shimeru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しめる、占める", "to comprise, to account for (shimeru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しる、知る", "to know (shiru)",
					"-",
					"ony: -",
					"kun: -",
					"six†",
					"-"},

				{"つかれる、疲れる", "to get tired (tsukareru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"でかける、出掛ける", "to go out, to depart (dekakeru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"はたらく、働く", "to work [e.g., at a job] (hataraku)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"はなす、放す、離す", "to let go of (hanasu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"やすむ、休む", "to rest, to take a break, to go to bed (yasumu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"わかれる、分かれる", "to split intoin, to be divided (wakareru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"わかれる、別れる", "to part, to separate, to break up (wakareru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"†", "conjugates as a u-verb",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"もう", "already (mō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"まだ", "still, yet (mada)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ずっと", "always (zutto)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"とても", "very (totemo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"こう", "like this (kō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"そう", "like that (sō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ああ", "in that other way (ā)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"どう", "how (dō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しばしば", "often (shibashiba)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"この", "this (kono)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"その", "that (sono)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"あの", "that (ano)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"どの", "which (dono)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"はい", "yes (hai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"いいえ", "no (iie)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"でも", "but (demo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しかし", "but, however (shikashi)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"そして", "and then, Then… (soshite)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"それに", "besides (soreni)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"なぜなら", "that is because, being because (nazenara)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"う、よう", "volitional ending [う for u-verbs, よう for ru-verbs]: \"Let's…\" or \"I will\" (u, yō)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"せる、させる", "causative ending [せる for u-verbs, させる for ru-verbs]: to make [someone do something], to allow (seru, saseru)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"れる、られる", "passive verb ending (reru, rareru)",
					"[れる for u-verbs, られる for ru-verbs]: to be <verbed> [e.g., 食べられる, \"to be eaten\"]",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"そうだ", "indicates that it seems the verb occurs [e.g., \"It seems he ate\"] (sōda)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"た", "informal past-tense (ta)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"たい", "indicates desire to perform verb (tai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"だろう", "indicates that it seems the verb occurs",
					" also used to ask whether the verb occurs (darō)",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ない、ん", "informal negative (nai, n)",
					"-",
					"ony: -",
					"kun: -",
					"six [ん is a slurred version and sounds a little masculine]",
					"-"},

				{"ぬ", "archaic informal negative [\"he hath\", \"thou didst\", etc.] (nu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ます", "formal non-past ending (masu)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"が", "subject marker, but (ga)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"で", "at, by (de)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"と", "and, with (to)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"に", "indirect object marker (ni)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"の", "possession marker, of (no)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"へ", "to (e)",
					"-",
					"ony: -",
					"kun: -",
					"[Note: へ is normally read he, but when used as this particle its reading changes to e]",
					"-"},

				{"まで", "to (made)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"から", "from (kara)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"より", "than (yori)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"を", "direct object marker (o)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"および、及び", "and",
					" as well as (oyobi)",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"か", "whether (ka)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かも", "might be, possible that (kamo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"そして", "and then (soshite)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"それとも", "or (soretomo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"だの", "things like <list of things>, including, such things as (dano)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"つつ", "ongoing occurrence (tsutsu)",
					"-",
					"ony: -",
					"kun: -",
					"[similar to ながら but has different tone, and both actions have equal weight]",
					"-"},

				{"て", "te form of verb or adjective [see explanation]",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"と", "when, if, that (to)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ながら", "while, though, both (nagara)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ならびに", "as well as (narabini)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"なり", "whether or not (nari)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"に", "to <somewhere>, by <someone> (ni)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"の", "possession (no)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ので", "so (node)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"また、又", "also, again (mata)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"または、又は", "or alternatively (matawa)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"も", "also, too (mo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"や", "and (ya)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ね", "emphasis and question marker, equivalent to \"right?\" (ne)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"か", "question marker (ka)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"な", "the copula particle used after quasi-adjectives (na)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"かしら", "I wonder (kashira)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"さ", "-ness (sa)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"っけ", "particle indicating that the speaker is trying to recall some information [\"What class is next -kke?\"] (-kke)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"こそ", "emphasis (koso)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"さえ", "even (sae)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"しか", "only (shika)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"すら", "even (sura)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"くらい、ぐらい", "approximately, about (kurai)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"だけ", "only, as much as (dake)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"だって", "however (datte)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"ったら", "casual topic marker (ttara)",
					"[colloquial form of to ittara (if you refer to ~, as for ~)",
					"ony: -",
					"kun: -",
					"six ",
					"-"},

				{"って", "said that (tte)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"でも", "also, or (demo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"どころ", "(particle used to indicate that what precedes it is an extreme example and strongly negates it)",
					"(dokoro)",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"など", "for example (nado)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"なら", "if [for verbs]",
					" subject marker [for nouns] (nara)",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"なんか", "casual undervalue, dislike, lack (nanka)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"なんて", "casual undervalue, dislike, lack (nante)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"は", "topic marker (wa)",
					"-",
					"ony: -",
					"[although ha is the hiragana used, wa is the pronunciation)",
					"six ",
					"-"},

				{"ばかり、ばっかり", "just, full of, only (bakari)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"まで", "until (made)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

				{"も", "too, also (mo)",
					"-",
					"ony: -",
					"kun: -",
					"-",
					"-"},

	*/
}
