package main

var fileOf_Current = []charSetStructKanji{

	{"僕 、ぼく", "I male", "male I",
		" -",
		" -",
		"僕は男です (I am a male)",
		"I, myself (boku, mainly used by males)"},

	{"俺 、おれ", "I male casual", "I male informal",
		" -",
		" -",
		"俺は男です (I am a male[between friends])",
		"I, myself (mainly used by males [informal/casual])"},

	{"弁護士 : べんごし", "lawyer", "attorney",
		" -",
		" -",
		" ",
		"Lawyer : べんごし"},

	{"看護師 : かんごし", "nurse", "Nurse",
		" -",
		"かんごし",
		" ",
		" "},

	{"看護婦 : かんごふ", "nurse female", "Female Nurse",
		" -",
		" -",
		" ",
		" "},

	{"警察官 : けいさつかん", "police officer", "cop",
		" -",
		" -",
		" ",
		"Police Officer : けいさつかん"},

	{"政治家 : せいじか", "politician", "statesman",
		" -",
		" -",
		" ",
		"Politician : せいじか"},

	{"歌手 : かしゅ", "singer", "vocalist",
		" -",
		" -",
		" ",
		" "},

	{"兵士 : へいし", "soldier", "warrior",
		" -",
		" -",
		" ",
		"soldier : へいし"},

	{"先生 : せんせい", "teacher", "instructor",
		" -",
		" -",
		" ",
		"Teacher (sensei) : せんせい"},

	{"教師 : きょうし ", "teacher academic", "academic teacher",
		" -",
		" -",
		" ",
		" "},

	{"時", "time", "hour",
		"ony: ジ(ji)",
		"kun: とき(toki)",
		"時 (time), 1時間 (1 hour), 時計 (clock, watch)",
		"time, hour, occasion"},

	{"時計", "clock", "watch",
		"じ",
		"kun: とき",
		"時計 watch",
		"time時 plus measure計 "},

	{"唇 、くちびる", "lips", "pucker",
		" ",
		" ",
		" ",
		" "},

	{"脛 、すね", "shin", "vulnerable leg bone",
		" ",
		" ",
		" ",
		" "},

	{"膝 、ひざ", "knee", "knee cap",
		" ",
		" ",
		" ",
		" "},

	{"腿 、もも", "thigh", "upper leg mussel",
		" ",
		" ",
		" ",
		" "},

	{"頭 、あたま", "head", "noggin",
		" ",
		" ",
		" ",
		" "},

	{"顔 、かお", "face", "mug",
		" ",
		" ",
		" ",
		" "},

	{"歯 、は", "tooth", "teeth, dentures, dentition",
		" ",
		" ",
		"歯医者 : しかい、、はいしゃ, dentist",
		" "},

	{"鼻 、はな", "nose", "snoz, beak, proboscis",
		" ",
		" ",
		" ",
		" "},

	{"め、目", "eye", "eyeball",
		" ",
		" ",
		" ",
		" "},
}
